version: '3'
services:
  top.api:
    image: top.api:latest
    container_name: topapi
    restart: always
    ports:
      - "3000:3000" //1- порт снаружи 2- порт внутри
    volumes:
      - "./.env:/opt/app/.env"
